# Generated by Django 3.0.4 on 2020-03-28 08:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VirtualMachineTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="VirtualMachine",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("vm-\\w+")],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="virtual_machines",
                        to="cloud.VirtualMachineTag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FirewallRule",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("fw-\\w+")],
                    ),
                ),
                (
                    "dest_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dest_firewall_rules",
                        to="cloud.VirtualMachineTag",
                    ),
                ),
                (
                    "source_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_firewall_rules",
                        to="cloud.VirtualMachineTag",
                    ),
                ),
            ],
        ),
    ]
